### ISSUE TITLE
pio install

### ISSUE THREAD

**Issue by Shden** [hunsalz/log4Esp#2]
Hi!

Tried to install into platformio.org:

`pio lib install 2110`

installation went ok:

> Library Storage: /Users/den/ShHarbor/esp/ShWade/thermosensor/.piolibdeps
LibraryManager: Installing id=2110
Downloading...
Unpacking...
log4Esp @ 1.0.2 has been successfully installed!

but the header isn't available on compilation:

> Compiling .pioenvs/esp12/src/thermosensor.cpp.o
src/thermosensor.cpp:34:21: fatal error: Log4Esp.h: No such file or directory
 

*****************************************************************
* Looking for Log4Esp.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Log4Esp.h"
* Web  > https://platformio.org/lib/search?query=header:Log4Esp.h
*
*****************************************************************
 
#include <Log4Esp.h>
^
compilation terminated.
*** [.pioenvs/esp12/src/thermosensor.cpp.o] Error 1
========================== [ERROR] Took 2.28 seconds ==========================

**Comment by eiannone** [comment]
Hi, I had a similar problem, and I think the problem lies in the library.json file, specifically in this line:

```
  "frameworks": "ESP8266",
```
That "ESP8266" framework string does not exists, and should be "arduino" instead (http://docs.platformio.org/en/latest/frameworks/index.html). 
Try modifying library.json file

**Comment by eiannone** [comment]
See https://github.com/hunsalz/log4Esp/pull/3
